version: "3"
services:
    mysql:
        image: mysql:latest
        restart: always
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ../sql:/docker-entrypoint-initdb.d/
        networks:
            - mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456  # change to your password!
            - MYSQL_DATABASE=smartTrade
        command: --default-authentication-plugin=mysql_native_password

    redis:
        image: redis:latest
        volumes:
            - ./data/redis:/data
        networks:
            - mysql
        ports:
            - "6379:6379"
        sysctls:
            - net.core.somaxconn=1024
    php-fpm81:
        build:
            context: .
            dockerfile: dockerfiles/php81/Dockerfile
        volumes:
            - ../:/var/www/html
            - ./conf/supervisor:/etc/supervisor/conf.d
        networks:
            - mysql
            - nginx
        ports:
            - "9000:9000"

    nginx:
        image: nginx:alpine
        volumes:
            - ../:/var/www/html
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./log/nginx:/var/log/nignx
            - ./ssl:/etc/nginx/ssl
        networks:
            - nginx
        ports:
            - "80:80"
            - "443:443"

networks:
    mysql:
        driver: bridge
    nginx:
        driver: bridge
